# follow instagram : yshrillbom_03
# yeahhh thx for follow
print("\033[33;1m ###################################################")
print("#----------------------{androsh-tools}-----------------------#")
print("#-- \033[31;1m follow-us ------------------------------------#")
print("#------------------------------------------------------------#")
print("#-- \033[31;1m tiktok-:-tidak-tersedia ----------------------#")
print("#-- \033[31;1m whastapp-:-6285141705599 ---------------------#")
print("#-- \033[31;1m instagram-:-yshrillbom_03 --------------------#")
print("#------------------------------------------------------------#")
print("#-- \033[31;1m developer-:-shermond-official ----------------#")
print("#-- \033[31;1m organisasi-:-C.G.H.H.A -----------------------#")
print("#-- \033[31;1m versi-:-1.3 ----------------------------------#")
print("#--------------((cyber-gray-hat-hacker-attacker))------------#")
print("#------------------------------------------------------------#")
print("##############################################################")
print("")
name = input("masukan nama anda : ")
print("")
print("selamat datang " + name)
print("")
print("silahkan pilih tools :")
print("")
print("1.prank screen")
print("")
print("2.android shermond(fitur utama)")
print("")
pilih = input("pilih : ")

if pilih == "1":
 print("masukan nomor atau username :")
 userno = input("nomor/username : ")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 print("mengirim virus ke " + userno + ".......selesai")
 
if pilih == "2":
 print("selamat datang di android shermond!!!")
 print("")
 print("silahkan pilih :")
 print("")
 print("1.about")
 print("")
 print("2.temen shermond")
 print("")
 print("3.credits")
 print("")
 pilih1 = input("pilih : ")

if pilih1 == "1":
 print("tentang :")
 print("")
 print("developer : shermond_official")
 print("")
 print("terminal yang digunakan dev : termux/terminal linux")
 print("")
 print("terimakasih untuk :")
 print("")
 print("1.pencipta termux")
 print("")
 print("2.penemu python")
 print("")
 print("3.TUHAN yang maha esa")

if pilih1 == "2":
 print("temen shermond")
 print("")
 print("1.luiz")
 print("2.kevin")
 print("3.william sky")
 print("4.ryuga gaming broww")
 print("5.mii")
 print("6.hams whangsaff")

if pilih1 == "3":
 print("credit")
 print("")
 print("---------------------credits-------------------")
 print("")
 print("developer : shermond")
 print("produser : shermond")
 print("copyright : shermond official")
