# follow instagram : yshrillbom_03
# yeahhh thx for follow
print("##############################################################")
print("#----------------------{androsh-tools}-----------------------#")
print("#--follow-us-------------------------------------------------#")
print("#------------------------------------------------------------#")
print("#--tiktok-:-tidak-tersedia-----------------------------------#")
print("#--whastapp-:-6285141705599----------------------------------#")
print("#--instagram-:-yshrillbom_03---------------------------------#")
print("#------------------------------------------------------------#")
print("#--developer-:-shermond-official-----------------------------#")
print("#--organisasi-:-C.G.H.H.A------------------------------------#")
print("#--versi-:-1.2-----------------------------------------------#")
print("#--------------((cyber-gray-hat-hacker-attacker))------------#")
print("#------------------------------------------------------------#")
print("##############################################################")
print("")
name = input("masukan nama anda : ")
print("")
print("selamat datang " + name)
print("")
print("silahkan pilih tools :")
print("")
print("1.prank screen")
print("")
print("2.android shermond(fitur utama)")
print("")
pilih = input("pilih : ")

if pilih == "1":
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")
 print("mengirim virus mematikan.....................selesai")

elif pilih == "2":
 print("selamat datang di android shermond!!!")
 print("")
 print("silahkan pilih :")
 print("")
 print("1.about")
 print("")
 print("2.temen shermond")
 print("")
 print("3.credits")
 print("")
 pilih1 = input("pilih : ")

elif pilih1 == "1":
 print("tentang :")
 print("")
 print("developer : shermond_official")
 print("")
 print("terminal yang digunakan dev : termux/terminal linux")
 print("")
 print("terimakasih untuk :")
 print("")
 print("1.pencipta termux")
 print("")
 print("2.penemu python")
 print("")
 print("3.TUHAN yang maha esa")

elif pilih1 == "2":
 print("temen shermond")
 print("")
 print("1.luiz")
 print("2.kevin")
 print("3.william sky")
 print("4.ryuga gaming broww")
 print("5.mii")
 print("6.hams whangsaff")

elif pilih1 == "3":
 print("credit")
 print("")
 print("---------------------credits-------------------")
 print("")
 print("developer : shermond")
 print("produser : shermond")
 print("copyright : shermond official")
